export default {
  INVALID_DELAY_MESSAGE_FORMAT: "INVALID DELAY MESSAGE FORMAT",
  OK: "OK",
  SUCCESSFULLY_INSERTED_MESSAGE: "MESSAGE INSERTED SUCCESSFULLY",
  ERROR_LOADING_ENV_FILE: "ERROR LOADING ENV FILE",
};
